FROM gradle:jdk11

WORKDIR /usr/src/server
RUN apt-get update && apt-get install -y --no-install-recommends inotify-tools=3.14-8 && rm -r /var/lib/apt/lists/*

EXPOSE 8080
CMD ["/bin/sh", "-c", "gradle build && gradle run & while inotifywait -r -e create,modify,moved_from,delete src; do pkill java; gradle build && gradle run & done"]
