FROM gradle:jdk11

WORKDIR /usr/src/server
RUN apt-get update && apt-get install -y --no-install-recommends inotify-tools=3.14-8 && rm -r /var/lib/apt/lists/*

EXPOSE 8080
ENTRYPOINT ["/bin/sh", "-c", "trap 'gradle --stop; exit' INT TERM; gradle test run & run_pid=\"$!\"; /bin/sh -c \"run_pid='$run_pid'; while inotifywait -r -e create,modify,moved_from,delete src; do kill \\\"\\$run_pid\\\"; gradle test run & run_pid=\\\"\\$!\\\"; done\" & while true; do tail -f /dev/null & wait $!; done"]
