version: "3.9"

services:
  proxy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - proxy
    depends_on:
      - frontend
  frontend:
    image: frontend
    build:
      context: ../frontend
      dockerfile: ../hosting/Dockerfile-frontend
    environment:
      VITE_BACKEND_BASE_URL: ${BACKEND_BASE_URL}
    networks:
      - proxy
    depends_on:
      - backend
  backend:
    image: backend
    build:
      context: ../backend
      dockerfile: ../hosting/Dockerfile-backend
    environment:
      PORT: 8080
      SENSO_API_BASE_URL: ${SENSO_API_BASE_URL}
      SENSO_API_KEY: ${SENSO_API_KEY}
    networks:
      - proxy

networks:
  proxy:
