version: "3.9"

services:
  proxy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - proxy
    depends_on:
      - frontend
  frontend:
    image: frontend
    build:
      context: ../frontend
      dockerfile: ../hosting/Dockerfile-frontend
    networks:
      - proxy
    depends_on:
      - backend
  backend:
    image: backend
    build:
      context: ../backend
      dockerfile: ../hosting/Dockerfile-backend
    networks:
      - proxy

networks:
  proxy:
