FROM gradle:jdk11 AS builder

WORKDIR /usr/src/server
COPY . .

RUN gradle shadowJar
RUN mv build/libs/backend-*-all.jar build/libs/backend.jar

FROM openjdk:11

WORKDIR $JAVA_HOME/lib
RUN mkdir data
COPY --from=builder /usr/src/server/build/libs/backend.jar ./backend.jar
COPY --from=builder /usr/src/server/data/cars.csv ./data/cars.csv

ENTRYPOINT ["java", "-jar", "backend.jar"]
