---
- name: Deploy the project
  hosts: all
  vars:
    ansible_password: '{{ lookup("env", "SERVER_PASSWORD") }}'
    frontend_branch: '{{ lookup("env", "FRONTEND_BRANCH") or "main" }}'
    backend_branch: '{{ lookup("env", "BACKEND_BRANCH") or "main" }}'
    hosting_branch: '{{ lookup("env", "HOSTING_BRANCH") or "main" }}'
  handlers:
    - name: build frontend
      command:
        chdir: ~/hosting
        cmd: docker-compose build frontend
      notify: restart compose if running
    - name: build backend
      command:
        chdir: ~/hosting
        cmd: docker-compose build backend
      notify: restart compose if running
    - name: Check status
      command:
        cmd: docker-compose ls
      register: compose_status
      changed_when: '"hosting" in compose_status.stdout'
      listen: restart compose if running
      notify: restart compose
    - name: restart compose
      import_tasks: ../tasks/restart-compose.yaml
  tasks:
    - name: Ensure the latest git, Docker, and docker-compose are installed
      package:
        name:
          - git
          - docker
          - docker-compose # TODO: unecessary once the docker version is recent enough to include compose as a subcommand
        state: latest
    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: true
    - name: Clone/update hosting
      git:
        dest: ~/hosting
        repo: https://github.com/tli-group-4-grimm/hosting
        update: true
      register: clone_hosting
      notify:
        - build frontend
        - build backend
    - name: Checkout hosting branch
      command:
        chdir: ~/hosting
        cmd: "git checkout {{ hosting_branch }}"
      register: checkout_hosting
      changed_when: '"Already on " not in checkout_hosting.stderr'
      notify:
        - build frontend
        - build backend
    - name: Clone/update frontend
      git:
        dest: ~/frontend
        repo: https://github.com/tli-group-4-grimm/frontend
        update: true
      register: clone_frontend
      notify: build frontend
    - name: Checkout frontend branch
      command:
        chdir: ~/frontend
        cmd: "git checkout {{ frontend_branch }}"
      register: checkout_frontend
      changed_when: '"Already on " not in checkout_frontend.stderr'
      notify: build frontend
    - name: Clone/update backend
      git:
        dest: ~/backend
        repo: https://github.com/tli-group-4-grimm/backend
        update: true
      register: clone_backend
      notify: build backend
    - name: Checkout backend branch
      command:
        chdir: ~/backend
        cmd: "git checkout {{ backend_branch }}"
      register: checkout_backend
      changed_when: '"Already on " not in checkout_backend.stderr'
      notify: build backend
