---
- name: Restart deployment
  hosts: all
  vars:
    ansible_password: '{{ lookup("env", "SERVER_PASSWORD") }}'
  tasks:
    - name: Restart compose
      import_tasks: ../tasks/restart-compose.yaml
