name: Deploy with Ansible
on:
  workflow_dispatch:
    inputs:
      hosting_branch:
        description: The branch to pull for the hosting repository
        required: false
        default: main
      frontend_branch:
        description: The branch to pull for the frontend repository
        required: false
        default: main
      backend_branch:
        description: The branch to pull for the backend repository
        required: false
        default: main
  repository_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ansible
        run: pip3 install ansible
      - name: Deploy with Ansible
        run: ansible-playbook -i "root@$SERVER_HOSTNAME", playbooks/deploy.yaml
        env:
          PUBLIC_BASE_URL: ${{ secrets.PUBLIC_BASE_URL }}
          SERVER_HOSTNAME: ${{ secrets.SERVER_HOSTNAME }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          ANSIBLE_HOST_KEY_CHECKING: False
