name: Restart with Ansible
description: Deploys the project to the server
on:
  workflow_dispatch:
jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ansible
        run: pip3 install ansible
      - name: Restart with ansible
        run: ansible-playbook -i "root@$SERVER_HOSTNAME", playbooks/restart.yaml
